// Date: 11/5/2013 8:35:50 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.ModEd.CreeperBot;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;


public class ModelCreeperBot extends ModelBase
{
  //fields
    ModelRenderer CreeperBot;
  
    public ModelCreeperBot()
    {
      textureWidth = 64;
      textureHeight = 32;
      
        CreeperBot = new ModelRenderer(this, 0, 0);
        CreeperBot.addBox(0F, 0F, 0F, 16, 16, 16);
        CreeperBot.setRotationPoint(0F, 0F, 0F);
        CreeperBot.setTextureSize(64, 32);
        CreeperBot.mirror = true;
        setRotation(CreeperBot, 0F, 0F, 0F);
    }
    
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
      super.render(entity, f, f1, f2, f3, f4, f5);
      setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      CreeperBot.render(f5);
    }
    
    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
    }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
	super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
